//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace curt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Work
    {
        public Nullable<int> Subjects_code { get; set; }
        public Nullable<int> Student_code { get; set; }
        public Nullable<int> disciplines_code { get; set; }
        public string Theme { get; set; }
        public Nullable<System.DateTime> YearDate { get; set; }
    
        public virtual Disciplines Disciplines { get; set; }
        public virtual Students Students { get; set; }
        public virtual Subjects Subjects { get; set; }
    }
}
