//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace curt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guide
    {
        public Nullable<int> subjects_id { get; set; }
        public Nullable<int> teachers_id { get; set; }
        public System.DateTime DateYear { get; set; }
    
        public virtual Subjects Subjects { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
