//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace curt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int Journal_id { get; set; }
        public Nullable<int> students_code { get; set; }
        public Nullable<int> StageOne { get; set; }
        public Nullable<int> StageTwo { get; set; }
        public Nullable<int> Result { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
