//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace curt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Courses_projectEntities : DbContext
    {
        private static Courses_projectEntities _context;
        public Courses_projectEntities()
            : base("name=Courses_projectEntities")
        {
        }
        public static Courses_projectEntities GetContext()
        {
            if (_context == null)
                _context = new Courses_projectEntities();
            return _context;

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course_Work> Course_Work { get; set; }
        public virtual DbSet<Disciplines> Disciplines { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Guide> Guide { get; set; }
        public virtual DbSet<Journal> Journal { get; set; }
        public virtual DbSet<Registr> Registr { get; set; }
        public virtual DbSet<SaveWork> SaveWork { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<Subjects> Subjects { get; set; }
        public virtual DbSet<Teachers> Teachers { get; set; }
    }
}
